Repository facebookexperimental/Recoil, pull requests merged in 2020-05, with the labels that each got.

#4 Add missing async keyword
  docs/docs/api-reference/core/useRecoilCallback.md
Labels: CLA Signed

#3 Set correct edit urls
  docs/docusaurus.config.js
Labels: CLA Signed

#9 docs: correct variable name in sample code
  docs/docs/basic-tutorial/selectors.md
Labels: CLA Signed

#8 fix useRecoilValue typo
  docs/docs/api-reference/core/useRecoilValue.md
Labels: CLA Signed

#20 docs: fix typo
  docs/docs/api-reference/core/useRecoilState.md
Labels: CLA Signed

#22 correct a text
  docs/docs/introduction/core-concepts.md
Labels: CLA Signed

#28 docs: use https for the website instead of http
  README.md
Labels: CLA Signed

#13 chore: Remove package-lock in order to use yarn.lock
  package-lock.json
Labels: CLA Signed

#39 Delete package-lock.json
  docs/package-lock.json
Labels: CLA Signed

#40 Document utilities
  docs/docs/api-reference/core/useRecoilState.md
  docs/docs/api-reference/core/useRecoilValue.md
  docs/docs/api-reference/core/useRecoilValueLoadable.md
  docs/docs/api-reference/core/useResetRecoilState.md
  docs/docs/api-reference/core/useSetRecoilState.md
  docs/docs/api-reference/utils/atomFamily.md
  docs/docs/api-reference/utils/selectorFamily.md
  docs/docs/guides/asynchronous-data-queries.md
  docs/sidebars.js
Labels: CLA Signed

#45 docs: fix async function usage
  docs/docs/guides/asynchronous-data-queries.md
Labels: CLA Signed

#50 Use React Europe video
  docs/src/pages/index.js
Labels: CLA Signed

#58 Document data flow graph and concurrent requests
  docs/docs/guides/asynchronous-data-queries.md
Labels: CLA Signed

#52 Fixed typo in atomFamily.md
  docs/docs/api-reference/utils/atomFamily.md
Labels: CLA Signed

#59 Stub for persistence
  docs/docs/guides/persistence.md
  docs/sidebars.js
Labels: CLA Signed

#62 Fix <RecoilRoot> typo
  docs/docs/guides/asynchronous-data-queries.md
Labels: CLA Signed

#68 Update `TodoItemCreator` in the examples
  docs/docs/basic-tutorial/atoms.mdx
Labels: CLA Signed

#72 feat(website): add DocSearch as recommended by docusaurus
  docs/docusaurus.config.js
Labels: CLA Signed

#79 fix typo
  docs/docs/api-reference/core/atom.md
Labels: CLA Signed

#53 Avoid window reference error in SSR
  src/util/Recoil_isNode.js
Labels: CLA Signed

#67 Add development build
  package.json
  rollup.config.js
  scripts/postbuild.js
  src/npm/index.js
Labels: CLA Signed

#64 fix selector reference
  src/recoil_values/Recoil_atom.js
Labels: CLA Signed

#81 feature(test): Adds jest as test script
  .babelrc
  .watchmanconfig
  package.json
  src/adt/__tests__/Recoil_ArrayKeyedMap-test.js
  src/caches/__tests__/Recoil_cacheMostRecent-test.js
  src/caches/__tests__/Recoil_cacheWithReferenceEquality-test.js
  src/caches/__tests__/Recoil_cacheWithValueEquality-test.js
  src/core/__tests__/Recoil_RecoilValueInterface-test.js
  src/core/__tests__/Recoil_core-test.js
  src/hooks/__tests__/Recoil_PublicHooks-test.js
  src/hooks/__tests__/Recoil_useRecoilCallback-test.js
  src/hooks/__tests__/Recoil_useRecoilInterface-test.js
  src/hooks/__tests__/Recoil_useRecoilStateReset-test.js
  src/hooks/__tests__/Recoil_useRecoilValueLoadable-test.js
  src/recoil_values/Recoil_WaitFor.js
  src/recoil_values/Recoil_error.js
  src/recoil_values/__tests__/Recoil_WaitFor-test.js
  src/recoil_values/__tests__/Recoil_atom-test.js
  src/recoil_values/__tests__/Recoil_atomFamily-test.js
  src/recoil_values/__tests__/Recoil_atomWithFallback-test.js
  src/recoil_values/__tests__/Recoil_constSelector-test.js
  src/recoil_values/__tests__/Recoil_errorSelector-test.js
  src/recoil_values/__tests__/Recoil_selector-test.js
  src/recoil_values/__tests__/Recoil_selectorFamily-test.js
  src/testing/Recoil_TestingUtils.js
  src/util/__tests__/Recoil_stableStringify-test.js
  yarn.lock
Labels: CLA Signed, tests

#86 Fix more tests
  .watchmanconfig
  package.json
  src/hooks/__tests__/Recoil_PublicHooks-test.js
  src/hooks/__tests__/Recoil_useRecoilCallback-test.js
  src/hooks/__tests__/Recoil_useRecoilValueLoadable-test.js
  src/recoil_values/__tests__/Recoil_atomFamily-test.js
  src/recoil_values/__tests__/Recoil_atomWithFallback-test.js
  src/recoil_values/__tests__/Recoil_selector-test.js
Labels: CLA Signed

#89 nit/fixing-misspelling - Fixing minor misspelling
  src/adt/Recoil_Loadable.js
  src/core/Recoil_Node.js
  src/core/Recoil_State.js
  src/recoil_values/Recoil_ScopedAtom.js
  src/recoil_values/Recoil_WaitFor.js
  src/recoil_values/Recoil_atom.js
  src/recoil_values/Recoil_selector_NEW.js
  src/util/__tests__/Recoil_stableStringify-test.js
Labels: CLA Signed

#83 Prettier
  .prettierrc
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  package.json
  rollup.config.js
  src/Recoil.js
  src/RecoilUtils.js
  src/components/Recoil_Link.react.js
  src/components/Recoil_RecoilRoot.react.js
  src/core/Recoil_Node.js
  src/core/Recoil_RecoilValue.js
  src/lib/Recoil_expectationViolation.js
  src/lib/Recoil_invariant.js
  src/lib/Recoil_recoverableViolation.js
  src/npm/index.js
  src/recoil_values/Recoil_WaitFor.js
  src/recoil_values/Recoil_atom.js
  src/recoil_values/Recoil_atomFamily.js
  src/recoil_values/Recoil_selectorFamily.js
  src/util/Recoil_PerformanceTimings.js
  src/util/Recoil__debug.js
  src/util/Recoil_gkx.js
  src/util/Recoil_mapIterable.js
  src/util/Recoil_recoverableViolation.js
  src/util/SchedulerTracing.js
  yarn.lock
Labels: CLA Signed

#100 [docs] Add quotes to atomFamily key in example
  docs/docs/api-reference/utils/atomFamily.md
Labels: CLA Signed, documentation

#98 [docs] removed "userID" from selector
  docs/docs/guides/asynchronous-data-queries.md
Labels: CLA Signed, documentation

#93 Fix minor misspelling
  src/components/Recoil_Link.react.js
  src/hooks/Recoil_Hooks.js
Labels: CLA Signed

#102 [docs] add key to `todoList.map` inside of `TodoList`
  docs/docs/basic-tutorial/atoms.mdx
Labels: CLA Signed, documentation

#96 [docs] Fix reference to `useSetRecoilState()` hook
  docs/docs/api-reference/core/atom.md
Labels: CLA Signed, documentation

#71 [docs] Update description and add example for useRecoilValue()
  docs/docs/api-reference/core/useSetRecoilState.md
Labels: CLA Signed

#106 [docs] Update syntax highlighting to use jsx
  docs/docs/api-reference/core/RecoilRoot.md
  docs/docs/api-reference/core/atom.md
  docs/docs/api-reference/core/isRecoilValue.md
  docs/docs/api-reference/core/selector.md
  docs/docs/api-reference/core/useRecoilCallback.md
  docs/docs/api-reference/core/useRecoilState.md
  docs/docs/api-reference/core/useRecoilValue.md
  docs/docs/api-reference/core/useSetRecoilState.md
  docs/docs/api-reference/utils/atomFamily.md
  docs/docs/api-reference/utils/selectorFamily.md
  docs/docs/guides/asynchronous-data-queries.md
Labels: CLA Signed, documentation

#116 [docs] Added parentheses to onClick function
  docs/docs/introduction/core-concepts.md
Labels: documentation

#60 [docs] edit content for useResetRecoilState() page
  docs/docs/api-reference/core/useResetRecoilState.md
Labels: CLA Signed, documentation

#88 GitHub actions
  .github/workflows/nodejs.yml
  README.md
Labels: CLA Signed

#124 [docs] Changed fieldname for useRecoilValueLoadable hook
  docs/docs/guides/asynchronous-data-queries.md
Labels: CLA Signed, documentation

#119 [docs] Add missing dot
  docs/docs/introduction/core-concepts.md
Labels: CLA Signed, documentation

#130 [docs] Minor typo
  docs/docs/introduction/core-concepts.md
Labels: documentation

#133 Fix badge URL in README
  README.md
Labels: CLA Signed

#109 Adds lint-staged
  package.json
  yarn.lock
Labels: CLA Signed

#148 Sync master with internal repo
  .watchmanconfig
  rollup.config.js
  src/Recoil_index.js
  src/adt/Recoil_ArrayKeyedMap.js
  src/core/Recoil_Node.js
  src/core/Recoil_RecoilValue.js
  src/hooks/__tests__/Recoil_PublicHooks-test.js
  src/hooks/__tests__/Recoil_useRecoilCallback-test.js
  src/hooks/__tests__/Recoil_useRecoilValueLoadable-test.js
  src/lib/Recoil_differenceSets.js
  src/lib/Recoil_equalsSet.js
  src/lib/Recoil_everySet.js
  src/lib/Recoil_expectationViolation.js
  src/lib/Recoil_filterMap.js
  src/lib/Recoil_intersectSets.js
  src/lib/Recoil_invariant.js
  src/lib/Recoil_isNode.js
  src/lib/Recoil_isPromise.js
  src/lib/Recoil_mapMap.js
  src/lib/Recoil_mergeMaps.js
  src/lib/Recoil_nullthrows.js
  src/lib/Recoil_recoverableViolation.js
  src/lib/Recoil_sprintf.js
  src/npm/index.js
  src/package.json
  src/recoil_values/Recoil_atom.js
  src/recoil_values/Recoil_atomFamily.js
  src/recoil_values/Recoil_atomWithFallback.js
  src/recoil_values/Recoil_const.js
  src/recoil_values/Recoil_error.js
  src/recoil_values/Recoil_selectorFamily.js
  src/recoil_values/Recoil_selector_NEW.js
  src/recoil_values/__flowtests__/Recoil_WaitFor-flowtest.js
  src/recoil_values/__tests__/Recoil_WaitFor-test.js
  src/recoil_values/__tests__/Recoil_atomFamily-test.js
  src/recoil_values/__tests__/Recoil_atomWithFallback-test.js
  src/recoil_values/__tests__/Recoil_selector-test.js
  src/testing/Recoil_TestingUtils.js
  src/util/Recoil_PerformanceTimings.js
  src/util/Recoil_Tracing.js
  src/util/Recoil__debug.js
  src/util/Recoil_differenceSets.js
  src/util/Recoil_equalsSet.js
  src/util/Recoil_everySet.js
  src/util/Recoil_expectationViolation.js
  src/util/Recoil_filterMap.js
  src/util/Recoil_gkx.js
  src/util/Recoil_invariant.js
  src/util/Recoil_isNode.js
  src/util/Recoil_isPromise.js
  src/util/Recoil_mapIterable.js
  src/util/Recoil_mapMap.js
  src/util/Recoil_mergeMaps.js
  src/util/Recoil_nullthrows.js
  src/util/Recoil_recoverableViolation.js
  src/util/Recoil_sprintf.js
  src/util/SchedulerTracing.js
Labels: CLA Signed

#90 [docs] document persistence.
  docs/docs/guides/persistence.md
  docs/docs/guides/persistence.mdx
Labels: CLA Signed, documentation

#157 [docs] Improve state persistence documentation
  docs/docs/guides/persistence.md
  docs/docs/guides/persistence.mdx
Labels: CLA Signed, documentation

#158 [docs] Improve documentation linking, stub for async state sync, ...
  docs/docs/api-reference/core/atom.md
  docs/docs/api-reference/core/useRecoilValueLoadable.md
  docs/docs/api-reference/utils/selectorFamily.md
  docs/docs/guides/asynchronous-data-queries.md
  docs/docs/guides/asynchronous-state-sync.md
  docs/docs/guides/persistence.md
  docs/sidebars.js
Labels: CLA Signed, documentation

#159 [docs] initial docs for syncing state
  docs/docs/guides/asynchronous-data-queries.md
  docs/docs/guides/asynchronous-state-sync.md
Labels: CLA Signed, documentation

#166 [docs] Fixed a typographical error
  docs/docs/guides/persistence.md
Labels: CLA Signed, documentation

#167 [docs] Fix bi-directional syncing example
  docs/docs/guides/asynchronous-state-sync.md
Labels: CLA Signed, documentation

#172 Update persistence.md
  docs/docs/guides/persistence.md
Labels: CLA Signed

#174 [docs] Improve docs for useRecoilCallback
  docs/docs/api-reference/core/useRecoilCallback.md
Labels: CLA Signed, documentation

#173 [docs] feedback from PR159
  docs/docs/guides/asynchronous-data-queries.md
  docs/docs/guides/asynchronous-state-sync.md
Labels: CLA Signed, documentation

#185 Fix typo: subs{ => c}ription
  docs/docs/guides/asynchronous-state-sync.md
Labels: documentation

#186 [docs] Explain parameter type restrictions for atomFamily and selectorFamily
  docs/docs/api-reference/utils/atomFamily.md
  docs/docs/api-reference/utils/selectorFamily.md
Labels: CLA Signed

#187 Update asynchronous-data-queries.md
  docs/docs/guides/asynchronous-data-queries.md
Labels: CLA Signed, documentation

#192 Docs
  docs/docs/guides/asynchronous-data-queries.md
Labels: CLA Signed, documentation

#196 Re-sync with internal repository
  .watchmanconfig
  src/package.json
Labels: CLA Signed, fh:direct-merge-enabled

#202 Fix a tiny typo in the tutorial
  docs/docs/basic-tutorial/performance.md
Labels: CLA Signed, documentation

#209 [docs] Further disclaim current persistence API
  docs/docs/guides/asynchronous-state-sync.md
  docs/docs/guides/persistence.md
Labels: CLA Signed, documentation
