Repository facebookexperimental/Recoil, pull requests merged in 2020-06, with the labels that each got.

#229 Fix tiny typos on useRecoilCallback.md
  docs/docs/api-reference/core/useRecoilCallback.md
Labels: CLA Signed, documentation

#240 Enable RSS & Atom feeds for blog
  docs/docusaurus.config.js
Labels: CLA Signed

#234 [docs] Asynchronous Example - remove unused get in selectorFamily
  docs/docs/guides/asynchronous-data-queries.md
Labels: CLA Signed, documentation

#207 [docs] fix typo in selectors.md
  docs/docs/basic-tutorial/selectors.md
Labels: CLA Signed, documentation

#203 [docs] recommends adding 'useRecoilCallback' to eslint config
  docs/docs/introduction/installation.md
Labels: CLA Signed, documentation

#261 [docs] Polish installation notes on eslint
  docs/docs/introduction/installation.md
Labels: CLA Signed, documentation

#267 [docs] Improve API Reference documentation
  docs/docs/api-reference/core/RecoilRoot.md
  docs/docs/api-reference/core/atom.md
  docs/docs/api-reference/core/selector.md
  docs/docs/api-reference/core/useRecoilCallback.md
  docs/docs/api-reference/core/useRecoilState.md
  docs/docs/api-reference/core/useRecoilStateLoadable.md
  docs/docs/api-reference/core/useRecoilValue.md
  docs/docs/api-reference/core/useRecoilValueLoadable.md
  docs/docs/api-reference/core/useResetRecoilState.md
  docs/docs/api-reference/core/useSetRecoilState.md
  docs/docs/api-reference/utils/atomFamily.md
  docs/docs/api-reference/utils/constSelector.md
  docs/docs/api-reference/utils/errorSelector.md
  docs/docs/api-reference/utils/noWait.md
  docs/docs/api-reference/utils/selectorFamily.md
  docs/docs/api-reference/utils/waitForAll.md
  docs/docs/api-reference/utils/waitForAny.md
  docs/docs/api-reference/utils/waitForNone.md
Labels: CLA Signed, documentation

#274 Fix selector() options "set: SetRecoilValue" type to "SetRecoilState"
  docs/docs/api-reference/core/selector.md
Labels: CLA Signed, documentation

#272 Minor grammar (missing period, commas)
  docs/docs/api-reference/core/selector.md
Labels: CLA Signed

#275 [docs] Fix reset typo in selector.md
  docs/docs/api-reference/core/selector.md
Labels: CLA Signed, documentation

#276 [docs] Remove parameters from utils API in sidebar
  docs/docs/api-reference/utils/constSelector.md
  docs/docs/api-reference/utils/errorSelector.md
  docs/docs/api-reference/utils/noWait.md
  docs/docs/api-reference/utils/waitForAll.md
  docs/docs/api-reference/utils/waitForAny.md
  docs/docs/api-reference/utils/waitForNone.md
Labels: CLA Signed, documentation

#273 Remove parameters from Hooks sidebar links
  docs/docs/api-reference/core/useRecoilCallback.md
  docs/docs/api-reference/core/useRecoilStateLoadable.md
  docs/docs/api-reference/core/useResetRecoilState.md
Labels: CLA Signed, documentation

#278 [docs] Fix a couple issues in persistence.md
  docs/docs/guides/persistence.md
Labels: CLA Signed, documentation

#285 [docs] Explain selectors more in API reference
  docs/docs/api-reference/core/selector.md
Labels: CLA Signed, documentation

#287 [docs] Improve atomFamily example with selectorFamily default
  docs/docs/api-reference/utils/atomFamily.md
Labels: CLA Signed, documentation

#323 [docs] Add destructuring example to selectorFamily docs
  docs/docs/api-reference/utils/selectorFamily.md
Labels: CLA Signed, documentation

#324 [docs] Document Pre-Fetching example
  docs/docs/api-reference/core/useRecoilCallback.md
  docs/docs/guides/asynchronous-data-queries.md
Labels: CLA Signed, documentation

#344 Fix typo in selector.md example
  docs/docs/api-reference/core/selector.md
Labels: CLA Signed

#334 [docs] Documentation for 0.0.9
  docs/blog/2020-06-18-0.0.9-released.md
  docs/docs/api-reference/core/Loadable.md
  docs/docs/api-reference/core/RecoilRoot.md
  docs/docs/api-reference/core/Snapshot.md
  docs/docs/api-reference/core/atom.md
  docs/docs/api-reference/core/isRecoilValue.md
  docs/docs/api-reference/core/selector.md
  docs/docs/api-reference/core/useGotoRecoilSnapshot.md
  docs/docs/api-reference/core/useRecoilCallback.md
  docs/docs/api-reference/core/useRecoilSnapshotAndSubscribe.md
  docs/docs/api-reference/core/useRecoilState.md
  docs/docs/api-reference/core/useRecoilStateLoadable.md
  docs/docs/api-reference/core/useRecoilTransactionObserver.md
  docs/docs/api-reference/core/useRecoilValue.md
  docs/docs/api-reference/core/useRecoilValueLoadable.md
  docs/docs/api-reference/utils/atomFamily.md
  docs/docs/api-reference/utils/constSelector.md
  docs/docs/api-reference/utils/noWait.md
  docs/docs/api-reference/utils/waitForAll.md
  docs/docs/api-reference/utils/waitForAny.md
  docs/docs/api-reference/utils/waitForNone.md
  docs/docs/guides/asynchronous-data-queries.md
  docs/docs/introduction/installation.md
  docs/sidebars.js
Labels: CLA Signed, documentation

#350 Blog typo
  docs/blog/2020-06-18-0.0.9-released.md
Labels: CLA Signed, documentation

#355 [docs] Documentation update for 0.0.10 release
  docs/blog/2020-06-18-0.0.10-released.md
  docs/docs/api-reference/core/Snapshot.md
  docs/docs/api-reference/core/useRecoilSnapshot.md
  docs/docs/api-reference/core/useRecoilTransactionObserver.md
  docs/sidebars.js
Labels: CLA Signed, documentation

#357 [docs] Add extra unstable note
  docs/docs/api-reference/core/useRecoilTransactionObserver.md
Labels: CLA Signed, documentation

#358 [docs] Minor blog formatting
  docs/blog/2020-06-18-0.0.10-released.md
Labels: documentation

#97 [docs] use full todoList for stats, not filteredTodoList.
  docs/docs/basic-tutorial/selectors.md
Labels: CLA Signed, documentation

#395 Fix typo in useRecoilState.md description
  docs/docs/api-reference/core/useRecoilState.md
Labels: CLA Signed, documentation

#404 Updating asynchronous-data-queries.md
  docs/docs/guides/asynchronous-data-queries.md
Labels: documentation

#411 [docs] Clarify <RecoilRoot> initializeState
  docs/docs/api-reference/core/RecoilRoot.md
Labels: documentation
