Repository facebookexperimental/Recoil, pull requests merged in 2021-05, with the labels that each got.

#1003 [docs/korean] Update motivation.md in KOR
  docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/motivation.md
Labels: CLA Signed

#1005 [docs/korean] Update core-concepts.md in KOR
  docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/core-concepts.md
Labels: CLA Signed, documentation

#1004 [docs/korean] Update installation.md in KOR
  docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/installation.md
Labels: CLA Signed, documentation

#1009 [docs/korean] Update useGetRecoilValueInfo.md
  docs/i18n/ko/docusaurus-plugin-content-docs/current/api-reference/core/useGetRecoilValueInfo.md
Labels: CLA Signed, documentation

#1007 Fix typo in intro.md
  docs/docs/basic-tutorial/intro.md
Labels: CLA Signed, documentation

#1002 Fix typo on homepage french translation
  docs/i18n/fr/code.json
Labels: CLA Signed, documentation

#1015 [docs] Remove redundant sidebar entries
  docs/sidebars.js
Labels: CLA Signed, documentation

#1016 Docs for 0.3.0 release
  docs/docs/api-reference/core/RecoilRoot.md
  docs/docs/api-reference/core/selector.md
Labels: CLA Signed, documentation

#1023 0.3.0 blog post
  docs/blog/2021-03-22-0.2.0-released.md
  docs/blog/2021-05-14-0.3.0-released.md
Labels: CLA Signed

#1025 chore(blog): add code block language
  docs/blog/2020-05-30-0.0.8-released.md
Labels: documentation

#1031 [Docs] Remove redundant Snapshots sidebar tab
  docs/sidebars.js
Labels: CLA Signed, documentation

#1047 Fix typo
  docs/i18n/fr/docusaurus-plugin-content-docs/current/guides/testing.md
Labels: CLA Signed

#1045 Fix typo at docs korean version
  docs/i18n/ko/docusaurus-plugin-content-docs/current/guides/asynchronous-data-queries.md
Labels: CLA Signed

#1043 Update selector.md
  docs/docs/api-reference/core/selector.md
Labels: CLA Signed, documentation

#1042 Update selector.md
  docs/docs/api-reference/core/selector.md
Labels: CLA Signed, documentation

#1041 Update atom.md
  docs/docs/api-reference/core/atom.md
Labels: CLA Signed, documentation

#1039 Update intro.md
  docs/i18n/ko/docusaurus-plugin-content-docs/current/basic-tutorial/intro.md
Labels: CLA Signed, documentation

#1033 [docs/korean] fix wrong translation & add missing translations
  docs/docs/api-reference/core/RecoilRoot.md
  docs/i18n/ko/code.json
  docs/i18n/ko/docusaurus-plugin-content-docs/current/api-reference/core/RecoilRoot.md
  docs/i18n/ko/docusaurus-plugin-content-docs/current/api-reference/core/selector.md
  docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/installation.md
  docs/i18n/ko/docusaurus-theme-classic/footer.json
  docs/i18n/ko/docusaurus-theme-classic/navbar.json
Labels: CLA Signed, documentation
