Repository facebookexperimental/Recoil, pull requests merged in 2021-11, with the labels that each got.

#1378 getting-started.mdx spelling mistake
  docs/i18n/fr/docusaurus-plugin-content-docs/current/introduction/getting-started.mdx
Labels: CLA Signed

#1373 [docs] Documentation for 0.5
  docs/blog/2021-07-30-0.4.0-release.md
  docs/blog/2021-08-26-0.4.1-release.md
  docs/blog/2021-11-03-0.5.0-release.md
  docs/docs/api-reference/core/Loadable.md
  docs/docs/api-reference/core/Snapshot.md
  docs/docs/api-reference/core/useGetRecoilValueInfo.md
  docs/docs/api-reference/core/useRecoilRefresher.md
  docs/docs/guides/asynchronous-data-queries.md
  docs/docs/guides/atom-effects.md
  docs/sidebars.js
  docs/yarn.lock
Labels: documentation, CLA Signed

#1376 Fix missing bracket in `testing.md` for `RecoilObserver`
  docs/docs/guides/testing.md
Labels: documentation, CLA Signed

#1392 [docs] Ignore generated files
  .gitignore
Labels: CLA Signed, build / infra

#1393 [docs] Fix typo in useRecoilRefresher()
  docs/docs/api-reference/core/useRecoilRefresher.md
Labels: documentation, CLA Signed

#1379 french spelling mistakes
  docs/i18n/fr/docusaurus-plugin-content-docs/current/basic-tutorial/atoms.mdx
Labels: documentation, CLA Signed

#1385 fix: typos in korean docs
  docs/i18n/ko/docusaurus-plugin-content-docs/current/api-reference/core/Loadable.md
  docs/i18n/ko/docusaurus-plugin-content-docs/current/api-reference/core/RecoilRoot.md
  docs/i18n/ko/docusaurus-plugin-content-docs/current/api-reference/utils/atomFamily.md
  docs/i18n/ko/docusaurus-plugin-content-docs/current/api-reference/utils/noWait.md
Labels: documentation, CLA Signed

#1398 [docs] Fix useRecoilRefresher()
  docs/docs/api-reference/core/useRecoilRefresher.md
  docs/docs/guides/asynchronous-data-queries.md
Labels: documentation, CLA Signed
