Repository facebookexperimental/Recoil, pull requests merged in 2022-10, with the labels that each got.

#2031 [docs] Link to SideGuide interactive tutorial
  docs/docs/basic-tutorial/intro.md
  docs/docusaurus.config.js
  docs/src/pages/resources.js
Labels: documentation, CLA Signed

#2033 [docs] make RecoilURLSyncTransit 'handlers' a stable constant, …
  docs/docs/recoil-sync/api/RecoilURLSyncTransit.md
Labels: documentation, CLA Signed

#2055 [docs] Clarify other hooks already support transitions
  docs/docs/guides/transitions.md
Labels: documentation, CLA Signed

#2036 [docs] Expose updateItems in RecoilSync's Listen Interface
  docs/docs/recoil-sync/api/RecoilSync.md
Labels: documentation, CLA Signed, Component: recoil-sync

#2060 [docs] Release docmentation for Recoil 0.7.6 and Recoil Sync 0.2
  docs/blog/2022-06-02-recoil-relay-0.1.0-release.md
  docs/blog/2022-06-21-recoil-sync-0.1.0-release.md
  docs/blog/2022-06-21-refine-0.1.0-release.md
  docs/blog/2022-10-06-recoil-sync-0.2.0-release.md
  docs/blog/2022-10-11-recoil-0.7.6-release.md
  docs/docs/api-reference/core/RecoilEnv.md
  docs/sidebars.js
Labels: documentation, CLA Signed

#2064 [docs] Improve GraphQL mutation documentation
  docs/docs/recoil-relay/graphql-effects.md
  docs/docs/recoil-relay/graphql-mutations.md
  docs/docs/recoil-relay/graphql-queries.md
Labels: documentation, CLA Signed, Component: recoil-relay

#2065 [docs/korean] update translate useRecoilTransaction.md to Korean
  docs/i18n/ko/docusaurus-plugin-content-docs/current/api-reference/core/useRecoilTransaction.md
Labels: CLA Signed
