Repository facebookexperimental/Recoil, pull requests merged in 2022-02, with the labels that each got.

#1593 [docs/korean] update legacy translation to latest content
  docs/i18n/ko/docusaurus-plugin-content-docs/current/guides/atom-effects.md
Labels: documentation

#1595 [docs/korean] add korean translation of [Guides/Testing] documentation
  docs/i18n/ko/docusaurus-plugin-content-docs/current/guides/testing.md
Labels: documentation, CLA Signed

#1592 Add note about retaining a snapshot in async selector jest tests
  docs/docs/guides/testing.md
Labels: documentation, CLA Signed

#1607 Fixed example at asynchronous-data-queries.md
  docs/docs/guides/asynchronous-data-queries.md
Labels: documentation, CLA Signed

#1497 [docs] Initial Refine documentation
  docs/docs/refine/Introduction.md
  docs/docs/refine/api/Advanced_Checkers.md
  docs/docs/refine/api/Checkers.md
  docs/docs/refine/api/Collection_Checkers.md
  docs/docs/refine/api/Primitive_Checkers.md
  docs/docs/refine/api/Utilities.md
  docs/docusaurus.config.js
  docs/sidebars.js
Labels: documentation, CLA Signed

#1618 [docs] Fix broken links
  docs/docs/refine/Introduction.md
  docs/docs/refine/api/Checkers.md
  docs/docs/refine/api/Utilities.md
Labels: documentation, CLA Signed

#1619 Improve test guide
  docs/docs/guides/testing.md
Labels: documentation, CLA Signed

#1622 [docs] Link preview docs to source
  docs/docs/recoil-sync/introduction.md
  docs/docs/refine/Introduction.md
Labels: documentation, CLA Signed

#1623 [docs] Better document React transitions
  docs/blog/2022-01-28-0.6.0-release.md
  docs/docs/api-reference/core/useRecoilState.md
  docs/docs/api-reference/core/useRecoilValue.md
  docs/docs/api-reference/core/useRecoilValueLoadable.md
  docs/docs/guides/transitions.md
  docs/docs/guides/usage-flow.md
  docs/docs/guides/usage-typescript.md
  docs/docs/guides/writing-test.md
  docs/sidebars.js
Labels: documentation, CLA Signed

#1624 [docs] Improve some Recoil Sync links
  docs/docs/recoil-sync/api/syncEffect.md
  docs/docs/recoil-sync/sync-effect.md
Labels: documentation, CLA Signed

#1626 Improved phrasing.
  docs/docs/basic-tutorial/selectors.md
Labels: documentation, CLA Signed

#1628 [docs] Clarify/cleanup some async snapshot docs.
  docs/docs/api-reference/core/useRecoilSnapshot.md
  docs/docs/guides/testing.md
Labels: documentation, CLA Signed

#1629 [docs] Polish Recol Sync store implementation examples
  docs/docs/recoil-sync/api/useRecoilSync.md
  docs/docs/recoil-sync/implement-store.md
Labels: documentation, CLA Signed

#1630 [Docs][Recoil Sync] Update API docs for reading undefines
  docs/docs/recoil-sync/api/RecoilURLSync.md
  docs/docs/recoil-sync/api/RecoilURLSyncTransit.md
  docs/docs/recoil-sync/api/useRecoilSync.md
Labels: documentation, CLA Signed

#1633 docs: fix "fallback" translation
  docs/i18n/zh-hans/docusaurus-plugin-content-docs/current/guides/asynchronous-data-queries.md
Labels: CLA Signed

#1637 [docs] Mention retaining snapshots for async selectors in release notes
  docs/blog/2022-01-28-0.6.0-release.md
Labels: documentation, CLA Signed

#1638 [docs][recoil-sync] Improve internal documentation links
  docs/docs/recoil-sync/api/useRecoilSync.md
  docs/docs/recoil-sync/introduction.md
Labels: documentation, CLA Signed
