Repository facebookexperimental/Recoil, pull requests merged in 2022-06, with the labels that each got.

#1830 [docs] recoil-relay 0.1 and recoil 0.7.3 Documentation
  .gitignore
  docs/blog/2022-03-25-0.7.0-release.md
  docs/blog/2022-04-12-0.7.1-release.md
  docs/blog/2022-04-14-0.7.2-release.md
  docs/blog/2022-06-01-recoil-0.7.3-release.md
  docs/blog/2022-06-02-recoil-relay-0.1.0-release.md
  docs/docs/guides/atom-effects.md
  docs/docs/recoil-relay/api/graphQLMutationEffect.md
  docs/docs/recoil-relay/api/graphQLQueryEffect.md
  docs/docs/recoil-relay/api/graphQLSelector.md
  docs/docs/recoil-relay/api/graphQLSelectorFamily.md
  docs/docs/recoil-relay/api/graphQLSubscriptionEffect.md
  docs/docs/recoil-relay/introduction.md
  docs/docs/recoil-sync/introduction.md
Labels: documentation, CLA Signed

#1837 docs: fix typo
  docs/docs/recoil-relay/graphql-effects.md
Labels: documentation, CLA Signed

#1836 [docs/korean] Update motivation.md
  docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/motivation.md
Labels: documentation, CLA Signed

#1861 [docs/korean] fix typo
  docs/i18n/ko/docusaurus-plugin-content-docs/current/guides/atom-effects.md
Labels: documentation, CLA Signed

#1855 [docs] Update recoil-sync docs to remove hooks interface.
  docs/docs/api-reference/core/RecoilRoot.md
  docs/docs/recoil-sync/api/RecoilSync.md
  docs/docs/recoil-sync/api/RecoilURLSync.md
  docs/docs/recoil-sync/api/RecoilURLSyncJSON.md
  docs/docs/recoil-sync/api/RecoilURLSyncTransit.md
  docs/docs/recoil-sync/api/syncEffect.md
  docs/docs/recoil-sync/api/useRecoilSync.md
  docs/docs/recoil-sync/api/useRecoilURLSync.md
  docs/docs/recoil-sync/api/useRecoilURLSyncJSON.md
  docs/docs/recoil-sync/api/useRecoilURLSyncTransit.md
  docs/docs/recoil-sync/implement-store.md
  docs/docs/recoil-sync/introduction.md
  docs/docs/recoil-sync/sync-effect.md
  docs/docs/recoil-sync/url-persistence.md
  docs/sidebars.js
Labels: documentation, CLA Signed

#1862 [docs] Minor recoil-sync tweaks
  docs/docs/recoil-sync/api/RecoilURLSync.md
  docs/docs/recoil-sync/api/RecoilURLSyncJSON.md
  docs/docs/recoil-sync/api/RecoilURLSyncTransit.md
Labels: documentation, CLA Signed

#1875 [docs] fix wrong function name setEvent -> setUser
  docs/docs/recoil-relay/graphql-selectors.md
Labels: CLA Signed

#1884 [docs] Document GraphQL Fragment queries
  docs/docs/recoil-relay/api/graphQLQueryEffect.md
  docs/docs/recoil-relay/api/graphQLSelector.md
  docs/docs/recoil-relay/api/graphQLSelectorFamily.md
  docs/docs/recoil-relay/graphql-effects.md
  docs/docs/recoil-relay/graphql-selectors.md
Labels: documentation, CLA Signed

#1885 [docs] Restructure recoil-relay documentation for clarity
  docs/blog/2022-06-01-recoil-0.7.3-release.md
  docs/blog/2022-06-02-recoil-relay-0.1.0-release.md
  docs/docs/recoil-relay/api/EnvironmentKey.md
  docs/docs/recoil-relay/api/RecoilRelayEnvironment.md
  docs/docs/recoil-relay/api/RecoilRelayEnvironmentProvider.md
  docs/docs/recoil-relay/api/graphQLQueryEffect.md
  docs/docs/recoil-relay/api/graphQLSelector.md
  docs/docs/recoil-relay/api/graphQLSelectorFamily.md
  docs/docs/recoil-relay/environment.md
  docs/docs/recoil-relay/graphql-effects.md
  docs/docs/recoil-relay/graphql-mutations.md
  docs/docs/recoil-relay/graphql-queries.md
  docs/docs/recoil-relay/graphql-selectors.md
  docs/docs/recoil-relay/graphql-subscriptions.md
  docs/docs/recoil-relay/introduction.md
  docs/docs/recoil-relay/preloaded-queries.md
  docs/sidebars.js
Labels: documentation, CLA Signed

#1895 [docs] Clarify proxy object for useRecoilCallback() interface.
  docs/docs/api-reference/core/useRecoilCallback.md
Labels: CLA Signed, dependencies
