Repository facebookexperimental/Recoil, pull requests merged in 2023-04, with the labels that each got.

#2201 [docs/ko] fix typo
  docs/i18n/ko/docusaurus-plugin-content-docs/current/guides/atom-effects.md
Labels: CLA Signed

#2194 Update environment.md
  docs/docs/recoil-relay/environment.md
Labels: CLA Signed

#2211 fix: atom initialized by promise updates downstream selectors
  packages/recoil/recoil_values/Recoil_atom.js
  packages/recoil/recoil_values/__tests__/Recoil_atom-test.js
Labels: bug, CLA Signed

#2215 use testRecoil in RecoilSync_URLCompound
  packages/recoil-sync/__tests__/RecoilSync_URLCompound-test.js
Labels: CLA Signed

#2220 Daily removal of unused Flow suppressions
  packages/recoil-relay/RecoilRelay_graphQLSelectorFamily.js
  packages/recoil-sync/RecoilSync.js
  packages/recoil-sync/__tests__/RecoilSync_URLCompound-test.js
  packages/recoil/adt/Recoil_Loadable.js
  packages/recoil/core/__tests__/Recoil_RecoilRoot-test.js
  packages/recoil/core/__tests__/Recoil_RecoilValueInterface-test.js
  packages/recoil/core/__tests__/Recoil_Retention-test.js
  packages/recoil/core/__tests__/Recoil_Snapshot-test.js
  packages/recoil/core/__tests__/Recoil_perf-test.js
  packages/recoil/hooks/__tests__/Recoil_Hooks_TRANSITION_SUPPORT_UNSTABLE-test.js
  packages/recoil/hooks/__tests__/Recoil_PublicHooks-test.js
  packages/recoil/hooks/__tests__/Recoil_useGetRecoilValueInfo-test.js
  packages/recoil/hooks/__tests__/Recoil_useGotoRecoilSnapshot-test.js
  packages/recoil/hooks/__tests__/Recoil_useRecoilCallback-test.js
  packages/recoil/hooks/__tests__/Recoil_useRecoilRefresher-test.js
  packages/recoil/hooks/__tests__/Recoil_useRecoilSnapshot-test.js
  packages/recoil/hooks/__tests__/Recoil_useRecoilStateReset-test.js
  packages/recoil/hooks/__tests__/Recoil_useRecoilTransactionObserver-test.js
  packages/recoil/hooks/__tests__/Recoil_useRecoilValueLoadable-test.js
  packages/recoil/hooks/__tests__/Recoil_useTransactionObservation_DEPRECATED-test.js
  packages/recoil/recoil_values/Recoil_atom.js
  packages/recoil/recoil_values/__tests__/Recoil_WaitFor-test.js
  packages/recoil/recoil_values/__tests__/Recoil_atom-test.js
  packages/recoil/recoil_values/__tests__/Recoil_selector-test.js
  packages/recoil/recoil_values/__tests__/Recoil_selectorHooks-test.js
  packages/refine/Refine_Checkers.js
  packages/refine/Refine_ContainerCheckers.js
  packages/refine/Refine_PrimitiveCheckers.js
  packages/refine/Refine_UtilityCheckers.js
  packages/shared/__test_utils__/Recoil_TestingUtils.js
Labels: CLA Signed, fb-exported

#2214 Add flag to skip circular dependency detection
  packages/recoil/core/Recoil_RecoilRoot.js
  packages/recoil/core/Recoil_State.js
  packages/recoil/recoil_values/Recoil_selector.js
Labels: CLA Signed, fb-exported

#2226 upgrade to flow v0.204.1
  .flowconfig
  flow-typed/jest.js
  flow-typed/npm/jest_v26.x.x.js
  package.json
  packages/shared/__test_utils__/Recoil_TestingUtils.js
  yarn.lock
Labels: CLA Signed

#2225 Pre-suppression for deploying 0.205.0 to www
  packages/recoil/recoil_values/Recoil_atom.js
  packages/recoil/recoil_values/Recoil_selector.js
Labels: CLA Signed, fb-exported
